# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f62464db71b09679522add5debd20b1a61ae97a223a1b98e1f51c9527a7714d4931ee954680ee98bf0e10e8cd441d3a4b66f87f40cf29011b6a3113751be463

test:
  secret_key_base: 69c224570737581dc10213c317c24fd31b48cefc4dc66f088201e0a5a037e578c7224d4c851c30d6aa308182045a446d7d9158c6e98583b887599a4928b294bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
